server:
  port: 9999
  debug: true
logging:
  config: 'config/logback.xml'
  level:
    org:
      springframework:
        security: DEBUG

spring:
  messages:
    basename: i18n/messages
  config:
    import: "database/db-ut.properties"
  freemarker:
    checkTemplateLocation: false
  oauth2:
    authorize-server-url: "https://localhost:8082/oauth/authorize"
    redirect-uri: "https://localhost:9999"
#  datasource:
#    url: jdbc:sqlserver://192.168.126.128:30516;databaseName=lizdb;encrypt=true;trustServerCertificate=true;
#    username: 'sa'
#    password: 'Mars@@@7811'
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: ${spring.database.url}
#    username: $spring.database.username}
#    password: ${spring.database.password}
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        ddl-auto: validate
#        naming:
#          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#          physical-naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        cache:
#          use_second_level_cache: false
#          use_query_cache: false
#        query:
#          substitutions: true 1, false 0  
#      database-platform: org.hibernate.dialect.SQLServer2012Dialect
  security:
    user:
      name: admin
      password: Mars@@@7811
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: google01
#            client-secret: google01
#          facebook:
#            client-id: facebook01
#            client-secret: facebook01
#    oauth2:
#      resource:
#        filter-order: 3
  thymeleaf:
    cache: false
scraw:
  stock-hist-fqdn: "https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=${DATE}&stockNo=${STOCKNO}"
  daily-tradedata-fqdn: 'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=csv&date=%s&type=ALL'
  stock-pure-code-file: "config/stockpurecode.txt"
  stock-histdata-file: "config/stockhistdata.txt"
  cacert-path: "config/certs/www.twse.com.tw.crt"
  startYear: 2010
  http-host: '65.108.250.129'
  http-port: '8080'
  https-host: '65.108.250.129'
  https-port: '8080'
  base-rand-time: 2000
  rand-time: 1000